# Generated by Django 6.0.1 on 2026-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level_cm', models.FloatField()),
                ('percentage', models.FloatField()),
                ('stage', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
