# Generated by Django 6.0.1 on 2026-01-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlevel',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='motor_status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=5),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
